Added pq to gem file
Ktechen/Dripbox pull request #3
Opened 2021-05-13 13:47 UTC by Ktechen

SQL Database is now postgre

2021-05-13 15:01 UTC, NoteFox requested changes
naja fast ^^
ich glaube du hast da nen "kleinen" schreibfehler gemacht

2021-05-13 15:01 UTC, notefox commented on Gemfile
> +gem 'pq'
wolltest du pg eingeben?
dieses hier?
https://rubygems.org/gems/pg/versions/0.18.4

2021-05-13 21:49 UTC, Ktechen commented on Gemfile
> +gem 'pq'
Oh, stimmt alles klar

2021-05-14 12:20 UTC, NoteFox requested changes
siehe Gemfile comment

2021-05-14 12:20 UTC, NoteFox commented on Gemfile
> +gem 'pg', '~> 0.18.4'
nimm mal die neuste version

gem 'pg', '~> 1.2', '>= 1.2.3'
https://rubygems.org/gems/pg/versions/1.2.3

2021-05-17 20:36 UTC, NoteFox approved these changes

2021-05-18 17:54 UTC, NoteFox approved these changes
works on my machine

2021-05-18 17:55 UTC, Franzi420 approved these changes

2021-05-20 14:42 UTC, MathisHTW approved these changes
<3

2021-05-20 15:09 UTC, merged